trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build and push Warp
      inputs:
        containerRegistry: 'trosk'
        repository: 'trosk/warp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildNumber)
          latest
        addPipelineData: false
        addBaseImageData: false