apiVersion: v1
kind: Pod
metadata:
  name: warp
spec:
  containers:
    - name: warp
      image: registry.hub.docker.com/trosk/warp:latest
      securityContext:
        capabilities:
          add:
            - MKNOD
            - AUDIT_WRITE
            - NET_RAW
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_PTRACE
      env:
        - name: ORGANIZATION
          value: string
        - name: AUTH_CLIENT_ID
          value: string
        - name: AUTH_CLIENT_SECRET
          value: string